import re

with open("index.html", "r", encoding="utf-8") as f:
    c = f.read()

# Metas
c = c.replace("<title>Hark</title>", "<title>SAVR | Hospitality Intelligence Platform</title>")
c = c.replace("At Hark, we are building the most advanced personal intelligence in the world.", "Turn invisible kitchen losses into visible, measurable savings.")
c = c.replace("content=\"Hark\"", "content=\"SAVR\"")

# Headings
c = c.replace("Hark is entering beta", "SAVR is entering beta")
c = c.replace("Hark © 2026", "SAVR © 2026")

# Social
c = c.replace("hark_labs", "savr_ai")
c = c.replace("hark-ai", "savr-ai")

# Paragraphs block
old_body = """<div class="prose-module-scss-module__s_qWJW__content prose-module-scss-module__s_qWJW__content" data-text-variant="display-6"><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">We are witnessing a worldwide transformation. The dialogue between humans and machines is fundamentally shifting.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">We now have intelligent systems that can use computers and are adept at reasoning. What becomes possible when computers start understanding and completing tasks on their&nbsp;own?</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">At Hark, we are building the most advanced personal intelligence in the world. Intelligence that begins to think like you and sometimes, ahead of you to offload your mental workload.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Imagine a system that interacts with the world exactly as you do: listening and speaking, seeing the world around it, building persistent memory, being proactive, and being able to touch and influence the world.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">We are crafting a new interface to artificial intelligence. A series of bespoke native hardware devices and agentic computers partnered with end-to-end speech, text and vision models with highly personalised memory.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">All our systems are multi-modal, built from scratch and capable of understanding and interacting in a natural way. Designed with detail and ultimate care.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Our ambitions are reflected in our incredible team. Our fingerprints already in everyone's hands, the services we use, and the interfaces we see, hear and touch.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">We want to bring this advanced super intelligence to everyone in the world.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">To develop this platform to make space for people to solve meaningful problems, create beautiful things, and spend time with those who matter most.</p></div>"""

new_body = """<div class="prose-module-scss-module__s_qWJW__content prose-module-scss-module__s_qWJW__content" data-text-variant="display-6"><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">India's hospitality sector faces a perfect storm of rising input costs. With LPG, edible oils, and proteins becoming more expensive, every kilogram of food wasted is bleeding margins and drastically hitting profitability.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Industry estimates suggest 4-16% of food purchased by Indian hotels ends up as waste. For a premium property with INR 8-12 Cr annual F&B revenue, that means losing INR 32-192 Lakhs annually to preventable inefficiencies.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Most hotel kitchens still operate blind. General Managers and F&B Directors know costs are rising, but lack granular, real-time visibility into exactly where waste occurs and how to adjust menus dynamically based on actual demand.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">SAVR is India's first all-in-one hospitality intelligence platform. We replace fragmented point solutions with a unified ecosystem spanning AI Waste Detection, Demand Forecasting, Dynamic Menu Pricing, and Smart Menu Intelligence.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Our computer vision cameras automatically identify, classify, and weigh every discarded item. This completely touchless operation generates real-time dashboards detailing exactly what is being wasted and why—enabling an immediate 30-50% food waste reduction.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Our Demand Forecasting module uses your historical data, occupancy rates, and local patterns to right-size production. We accurately predict how many covers to expect per meal period, saving 15-25% in overproduction costs instantly.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">SAVR's Dynamic Menu Pricing intelligently analyses contribution margins, prep time, and demand patterns to confidently recommend optimal pricing for each dish. As a result, slow movers are rotated out, while high-demand items deliver maximum profitability.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">We close the loop: waste detection data feeds directly into menu planning. If butter chicken is consistently wasted, the system automatically suggests replacements so your menu gets smarter every single week without relying purely on chef intuition.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Built specifically for Indian hotel economics, SAVR delivers measurable P&L impact instead of hype. With our convenient OPEX subscription model, the system pays for itself within the first month of full deployment.</p></div>"""

c = c.replace(old_body, new_body)

with open("index.html", "w", encoding="utf-8") as f:
    f.write(c)

print("Replacement Complete")
