import re

with open("index.html", "r", encoding="utf-8") as f:
    c = f.read()

# Paragraphs block
pattern = r'(<div class="prose-module-scss-module__s_qWJW__content prose-module-scss-module__s_qWJW__content" data-text-variant="display-6">).*?(</div>)'

new_content = """<p class="portable-text-module-scss-module__2yjBQq__basicParagraph">India's hospitality sector faces rising input costs. With LPG, edible oils, and proteins becoming more expensive, food waste is bleeding margins.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Industry estimates suggest 4-16% of food purchased by Indian hotels ends up as waste. For a premium property with INR 8-12 Cr annual F&B revenue, that means losing INR 32-192 Lakhs annually to preventable inefficiencies.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Most hotel kitchens still operate blind. General Managers and F&B Directors know costs are rising, but lack granular, real-time visibility into exactly where waste occurs and how to adjust menus dynamically based on actual demand.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">SAVR is India's first all-in-one hospitality intelligence platform. We replace fragmented point solutions with a unified ecosystem spanning AI Waste Detection, Demand Forecasting, Dynamic Menu Pricing, and Smart Menu Intelligence.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Our computer vision cameras automatically identify, classify, and weigh every discarded item. This completely touchless operation generates real-time dashboards detailing exactly what is being wasted and why—enabling an immediate 30-50% food waste reduction.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Our Demand Forecasting module uses your historical data, occupancy rates, and local patterns to right-size production. We accurately predict how many covers to expect per meal period, saving 15-25% in overproduction costs instantly.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">SAVR's Dynamic Menu Pricing intelligently analyses contribution margins, prep time, and demand patterns to confidently recommend optimal pricing for each dish. As a result, slow movers are rotated out, while high-demand items deliver maximum profitability.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">We close the loop: waste detection data feeds directly into menu planning. If butter chicken is consistently wasted, the system automatically suggests replacements so your menu gets smarter every single week without relying purely on chef intuition.</p><p class="portable-text-module-scss-module__2yjBQq__basicParagraph">Built specifically for Indian hotel economics, SAVR delivers measurable P&L impact. With our OPEX subscription model, the system pays for itself within the first month of full deployment.</p>"""

c, count = re.subn(pattern, r'\1' + new_content + r'\2', c, flags=re.DOTALL)
print("Replaced:", count)

with open("index.html", "w", encoding="utf-8") as f:
    f.write(c)
